# ChunkEraser Configuration file

# General settings
General:

  # Enable or disable the plugin
  enabled: false

  # Cooldown time in seconds before chunk get erased
  cooldown: 10

  # The player chunk distance radius for chunk selection
  playerChunkDistance: 10

  # If true, erases chunks from all players' view distance (remove one chunk for each player)
  # If false, pick random player and erase chunk from his view distance (remove one chunk each time)
  forAllPlayers: false

  # If true, increases the erased chunks number each round
  increaseEachTime: false

  # If true, sends a notification message to all players when chunk is being erased
  notifyPlayers: true

  # Keeps track of chunk removal iterations
  iterations: 0

# BossBar settings
BossBar:

  # Enable or disable the boss bar display
  enabled: true

  # Boss bar title
  title: "%TIMER% seconds are left"

  # Boss bar color
  # Can be use: 'BLUE', 'RED', 'PINK', 'YELLOW', 'GREEN', 'PURPLE', 'WHITE'
  color: BLUE

  # Boss bar style
  # Can be use: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  style: SOLID

# Action bar settings
ActionBar:

  # Enable or disable the action bar message
  enabled: false

  # Action bar message with MiniMessage placeholders for formatting
  # You can edit messages that use MiniMessage in here https://webui.advntr.dev/
  message: "<blue>Chunks being erased in <gold>%TIMER%</gold> seconds!</blue>"

# Messages (Uses MiniMessage)
# You can edit messages that use MiniMessage in here https://webui.advntr.dev/
Messages:

  # Chunk erased notification message
  chunkErasedNotification: "<aqua>A chunk has been <hover:show_text:'<gold>at</gold> <green>%CHUNK.X%</green>, <green>%CHUNK.Z%</green>'>erased!</hover></aqua>"

  # No permission message
  NoPerm: "<red>You lack the permission <dark_red>%PERM%</dark_red>!</red>"

  # execute command from console / anything that is not the player
  NoPlayer: "<red>You can't do that through the <dark_red>%EXECUTER%</dark_red>!</red>"

# Sound settings
Sound:

  # Enable or disable sound effect
  enabled: true

  # Sound type (refer to https://jd.papermc.io/paper/1.21.3/org/bukkit/Sound.html)
  soundType: "ENTITY_ENDER_DRAGON_GROWL"

  # Sound volume (0 = no sound, higher values = louder)
  volume: 10.0

  # Sound pitch (1 = normal, higher = higher pitched, lower = lower pitched)
  pitch: 1.0

  # If true, plays the sound for all players when chunk get erased
  # If false, plays the sound in the chunk location so just nearby players would hear it.
  allPlayers: false

# Log settings
Logs:

  # Enable or disable logging
  enabled: true

  # Log entry format with placeholders for chunk coordinates, world name, and timestamp
  logEntry: "[%TIME%] Erased chunk at {%CHUNK.X%, %CHUNK.Z%} in world {%CHUNK.WORLD%} near player: {%PLAYER%}\n"

  # Path to the log file
  logFilePath: "plugins/ChunkEraser/logs.txt"