# Configuration File

General:
  enabled: false # toggle the plugin on or off
  cooldown: 10 # Time in seconds

BossBar:
  enabled: true # Toggle the bossbar on or off
  title: "<timer> seconds are left" # the title of the bossbar
  color: BLUE # the color of the bossbar
  style: SOLID # the style of the bossbar - can be SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20