name: ChunkEraser
author: olios
version: '${project.version}'
main: me.olios.plugins.chunkeraser.ChunkEraser
api-version: 1.20

commands:
  chunkeraser:
    aliases:
      - ce
    description: Main command for the ChunkEraser plugin.
    usage: /<command> <subcommand>
    permission: ChunkEraser.admin

permissions:
  ChunkEraser.*:
    default: op